server:
  port: 8084

spring:
  application:
    name: skill-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/skillsync_skill
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: simple

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

  servers:
    - url: http://api-gateway:8080/skills
      description: Via API Gateway
    - url: http://skill-service:8084
      description: Direct
